# Generated by Django 4.1.4 on 2023-01-28 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_products_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_img_one', models.ImageField(upload_to='')),
                ('Product_img_two', models.ImageField(upload_to='')),
                ('Product_img_three', models.ImageField(upload_to='')),
                ('Product_img_four', models.ImageField(upload_to='')),
                ('Product_name', models.TextField()),
                ('Product_price', models.FloatField()),
                ('Product_description', models.TextField()),
                ('Product_Quantity', models.IntegerField(max_length=5)),
                ('Product_category', models.CharField(max_length=100)),
                ('Product_tags', models.CharField(max_length=50)),
                ('Product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.products')),
            ],
        ),
    ]
