# Generated by Django 4.1.4 on 2023-01-28 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_product_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_details',
            name='id',
        ),
        migrations.AlterField(
            model_name='product_details',
            name='Product_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='Product_image',
            field=models.ImageField(default='', upload_to='media'),
        ),
    ]
