# Generated by Django 4.1.4 on 2023-01-28 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_product_details_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_details',
            old_name='Product_id',
            new_name='P_id',
        ),
    ]
