# Generated by Django 4.1.4 on 2023-01-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_rename_product_id_product_details_p_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_details',
            name='P_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
