# Generated by Django 4.1.4 on 2023-01-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_product_details_p_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_details',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product_details',
            name='P_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product_details',
            name='Product_Quantity',
            field=models.IntegerField(),
        ),
    ]
