# Generated by Django 4.1.4 on 2023-01-28 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_product_details_id_alter_product_details_p_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_details',
            name='P_id',
        ),
    ]
