# Generated by Django 4.1.4 on 2023-01-31 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_remove_product_details_p_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='registerOrders',
            fields=[
                ('o_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('brownie', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('date', models.CharField(max_length=30)),
            ],
        ),
    ]
